<a href="https://colab.research.google.com/github/RajeshMTRA/ml-projects/blob/main/Decision_Tree_Regression_RM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Datasets/Salary Data (1).csv')

In [ ]:
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object 
 2   Education Level      373 non-null    object 
 3   Job Title            373 non-null    object 
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB


In [ ]:
df.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Years of Experience']=df['Years of Experience'].fillna(df['Years of Experience'].mean())

In [ ]:
most_freq_cat = df['Gender'].mode().iloc[0]
df['Gender'].fillna(most_freq_cat, inplace=True)

most_freq_cat = df['Education Level'].mode().iloc[0]
df['Education Level'].fillna(most_freq_cat, inplace=True)

most_freq_cat = df['Job Title'].mode().iloc[0]
df['Job Title'].fillna(most_freq_cat, inplace=True)

In [ ]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
df['Gender'] = le.fit_transform(df['Gender'])
df['Education Level'] = le.fit_transform(df['Education Level'])
df['Job Title'] = le.fit_transform(df['Job Title'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  375 non-null    float64
 1   Gender               375 non-null    int64  
 2   Education Level      375 non-null    int64  
 3   Job Title            375 non-null    int64  
 4   Years of Experience  375 non-null    float64
 5   Salary               375 non-null    float64
dtypes: float64(3), int64(3)
memory usage: 17.7 KB


In [ ]:
df

Age  Gender  Education Level  Job Title  Years of Experience    Salary
0    32.0       1                0        159                  5.0   90000.0
1    28.0       0                1         17                  3.0   65000.0
2    45.0       1                2        130                 15.0  150000.0
3    36.0       0                0        101                  7.0   60000.0
4    52.0       1                1         22                 20.0  200000.0
..    ...     ...              ...        ...                  ...       ...
370  35.0       0                0        131                  8.0   85000.0
371  43.0       1                1         30                 19.0  170000.0
372  29.0       0                0         70                  2.0   40000.0
373  34.0       1                0        137                  7.0   90000.0
374  44.0       0                2        110                 15.0  150000.0

[375 rows x 6 columns]

In [ ]:
df.describe()

Age      Gender  Education Level   Job Title  \
count  375.000000  375.000000       375.000000  375.000000   
mean    37.431635    0.522667         0.533333   89.629333   
std      7.050146    0.500153         0.722691   46.599427   
min     23.000000    0.000000         0.000000    0.000000   
25%     31.500000    0.000000         0.000000   50.000000   
50%     36.000000    1.000000         0.000000   94.000000   
75%     44.000000    1.000000         1.000000  132.000000   
max     53.000000    1.000000         2.000000  173.000000   

       Years of Experience         Salary  
count           375.000000     375.000000  
mean             10.030831  100577.345845  
std               6.539452   48110.856588  
min               0.000000     350.000000  
25%               4.000000   55000.000000  
50%               9.000000   95000.000000  
75%              15.000000  140000.000000  
max              25.000000  250000.000000

In [ ]:
x = df.drop(columns = ['Salary'])

In [ ]:
y = df['Salary']

In [ ]:
x

Age  Gender  Education Level  Job Title  Years of Experience
0    32.0       1                0        159                  5.0
1    28.0       0                1         17                  3.0
2    45.0       1                2        130                 15.0
3    36.0       0                0        101                  7.0
4    52.0       1                1         22                 20.0
..    ...     ...              ...        ...                  ...
370  35.0       0                0        131                  8.0
371  43.0       1                1         30                 19.0
372  29.0       0                0         70                  2.0
373  34.0       1                0        137                  7.0
374  44.0       0                2        110                 15.0

[375 rows x 5 columns]

In [ ]:
y

0       90000.0
1       65000.0
2      150000.0
3       60000.0
4      200000.0
         ...   
370     85000.0
371    170000.0
372     40000.0
373     90000.0
374    150000.0
Name: Salary, Length: 375, dtype: float64

**In DECISION TREE, usually no need to **SCALE** the dataset.**

# **k-Fold cross validation**

In [ ]:
from sklearn.tree import DecisionTreeRegressor
DTregressor = DecisionTreeRegressor(criterion = 'squared_error', max_depth = 10, min_samples_split = 2, min_samples_leaf=1, max_features=None, max_leaf_nodes=None, min_impurity_decrease=0.0)

# **Parameters:**

**criterion: {“squared_error”, “friedman_mse”, “absolute_error”, “poisson”}, default=”squared_error”**

Measuring the impurity(gini, entropy) during the split

**max_depth: int, default=None**

the max depth of tree, the number of splitting process.

**min_samples_split: int or float, default=2**

The minimum number of samples required to split an internal node.

**min_samples_leaf: int or float, default=1**

the nodes at the last of the decision tree must have at least one sample. Except this, the leaf node will be garbage, and decision should be made based on previous nodes.

**max_features: int, float or {“sqrt”, “log2”}, default=None**

The number of features to consider when looking for the best split (based on the value of impurity of the features and comparing them):

If int, then consider max_features features at each split.

If float, then max_features is a fraction and max(1, int(max_features * n_features_in_)) features are considered at each split.

If “sqrt”, then max_features=sqrt(n_features).

If “log2”, then max_features=log2(n_features).

**If None, then max_features=n_features.**

**max_leaf_nodes: int, default=None**

If None then unlimited number of leaf nodes. If mentioned a figure, for example 100, then there will be highest 100 leaf nodes allowed.

**min_impurity_decrease: float, default=0.0**

A node will be split if this split induces a decrease of the impurity greater than or equal to this value.

At each split, impurity normally decreases. Lets say, the value of this parameter is 0.4. If from one split to next split, the impurity doesnt decrease by at least 0.4, the split action wont be allowed.



In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

k_fold = KFold(10)

result1 = cross_val_score(DTregressor, x, y, cv=k_fold, scoring = 'neg_mean_squared_error')
# between two negative mean squared error, lets say -4 and -5, the bigger one, -4 is BETTER.

result2 = cross_val_score(DTregressor, x, y, cv=k_fold, scoring = 'neg_mean_absolute_percentage_error')
# Like the above one, higher value is better.

result3 = cross_val_score(DTregressor, x, y, cv=k_fold, scoring = 'r2')

In [ ]:
result1 # negative MSE

array([-6.47543174e+08, -9.01539478e+08, -3.92194799e+08, -2.55357523e+08,
       -1.44339657e+08, -1.83588963e+08, -1.21892471e+08, -7.07750828e+07,
       -8.52590025e+07, -3.35884418e+08])

In [ ]:
result2 # negative MAPE

array([-0.20457472, -0.17938142, -0.16174661, -0.11210863, -0.12552635,
       -0.10171331, -2.77469427, -0.05702801, -0.04811942, -0.06614169])

In [ ]:
overall_mae_percentage = sum(result2) / len(result2)
print(abs(overall_mae_percentage)*100)

38.31034446534768


In [ ]:
result3

array([0.75196871, 0.63070105, 0.85217093, 0.88258736, 0.92803303,
       0.93422337, 0.94318935, 0.97018503, 0.95879065, 0.89571404])

In [ ]:
overall_r2 = sum(result3) / len(result3)
print(overall_r2)

0.8747563506095629


The accuracies arent good. We can improve them by changing the hyper parameters of DT Regressor. This is called **HYPER PARAMETER TUNING**.

**find what metrics support**

In [ ]:
import sklearn
sklearn.metrics.get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',